image:
  file: .gitpod.Dockerfile
tasks:
  - init: >-
      abtnode init -f --mode debug --no-https && cd demo && mix deps.get && cd
      assets && npm install && cd ../..
    command: abtnode start && BLOCKLET_START_TIMEOUT=3600 abtnode dev
ports:
  - port: 8080
    onOpen: ignore
  - port: 8089
    onOpen: ignore
  - port: 8090
    onOpen: ignore
